datagrid:
    issues-grid:
        source:
            acl_resource: bap_bts.issue_view
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - issue.type
                    - priority.name as priorityName
                    - resolution.name as resolutionName
                    - reporter.username as reporterName
                    - assignee.username as assigneeName
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: BAPSimpleBTSBundle:Issue, alias: issue }
                join:
                    inner:
                        - { join: issue.priority, alias: priority }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
                    left:
                        - { join: issue.resolution, alias: resolution }
        columns:
            code:
                label: bts.issue.code.label
            summary:
                label: bts.issue.summary.label
            type:
                label: bts.issue.type.label
            priorityName:
                label: bts.priority.name.label
            resolutionName:
                label: bts.resolution.name.label
            reporterName:
                label: bts.issue.reporter.label
            assigneeName:
                label: bts.issue.assignee.label
            createdAt:
                label: bts.issue.created.label
                frontend_type: datetime
            updatedAt:
                label: bts.issue.updated.label
                frontend_type: datetime
        properties:
            id: ~
#            update_link:
#                type: url
#                route: bap_bts.issue_update
#                params:
#                    - id
#            view_link:
#                type: url
#                route: bap_bts.isssue_view
#                params:
#                    - id
#            delete_link:
#                type: url
#                route: inventory_api_delete_vehicle
#                params:
#                    - id

        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                type:
                    data_name: issue.type
                priorityName:
                    data_name: priority.sortOrder
                resolutionName:
                    data_name: resolution.name
                reporterName:
                    data_name: reporter.username
                assigneeName:
                    data_name: assignee.username
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                summary:
                    type: string
                    data_name: issue.summary
                type:
                    type: choice
                    data_name: issue.type
                    options:
                        field_options:
                            choices:
                                "BAP\SimpleBTSBundle\Entity\Issue::TYPE_STORY":   bts.issue.type.story
                                "BAP\SimpleBTSBundle\Entity\Issue::TYPE_TASK":    bts.issue.type.task
                                "BAP\SimpleBTSBundle\Entity\Issue::TYPE_SUBTASK": bts.issue.type.subtask
                                "BAP\SimpleBTSBundle\Entity\Issue::TYPE_BUG":     bts.issue.type.bug
                priorityName:
                    type: entity
                    data_name: priority
                    options:
                        field_options:
                            class: BAPSimpleBTSBundle:IssuePriority
                            property: name
                resolutionName:
                    type: entity
                    data_name: resolution
                    options:
                        field_options:
                            class: BAPSimpleBTSBundle:IssueResolution
                            property: name
                createdAt:
                    type: datetime
                    data_name: issue.createdAt
                updatedAt:
                    type: datetime
                    data_name: issue.updatedAt

#        actions:
#            view:
#                type:          navigate
#                label:         View
#                link:          view_link
#                icon:          eye-open
#                acl_resource:  inventory.vehicle_view
#                rowAction:     true
#            update:
#                type:          navigate
#                label:         Update
#                link:          update_link
#                icon:          edit
#                acl_resource:  inventory.vehicle_update
#            delete:
#                type:          delete
#                label:         Delete
#                link:          delete_link
#                icon:          trash
#                acl_resource:  inventory.vehicle_delete
