parameters:
#    bap_simple_bts.example.class: BAP\SimpleBTSBundle\Example

services:
#    bap_simple_bts.example:
#        class: %bap_simple_bts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
