services:
    bap_bts.issue_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - BAP\SimpleBTSBundle\Entity\Issue
            - "@doctrine.orm.entity_manager"
